### ISSUE TITLE
Very Critical Issue!!!!eleven!!!

### ISSUE THREAD

**Issue by phil-lopreiato** [twood02/atometer#1]
Where did you get the gif in the readme? I love it

**Comment by twood02** [comment]
~~I carefully hand painted it.~~

it just shows up by default when you generate a new package for atom.  More here: https://atom.io/

Quit stalking me and go back to work!

**Comment by nks5295** [comment]
An addition to this critical issue - why are we counting key strokes? Can this be a competition?!

**Comment by twood02** [comment]
haven't you always wanted to know how many keys you type a day in your editor?  How many miles you've traveled with your arrow keys?

I think all programs should come with odometers.

**Comment by nks5295** [comment]
i don't think i want zsh to tell me that.. it'll scare me and make me feel like i have less of a life than i believe to have.

**Comment by phil-lopreiato** [comment]
> ![screen shot 2015-06-26 at 10 42 49 am](https://cloud.githubusercontent.com/assets/2754863/8379762/1ec445ee-1bf0-11e5-951c-f836141ef3c1.png)

:cry:
