### ISSUE TITLE
Daily?

### ISSUE THREAD

**Issue by Falieson** [twood02/atometer#4]
Does the atometer reset every day? Looking at 7000 key strokes and I have to assume that's from yesterday (installed plugin day).

**Comment by twood02** [comment]
In theory they never reset, but in practice I find that they reset randomly, possibly when new versions of atom are installed. Strange things can also happen when atom is opened for multiple projects/windows.

In short: a lot of things probably aren't working right, I probably shouldn't have actually released this to the public ;)

**Comment by Falieson** [comment]
Hahaha - well I still like the counter for the window. Don't know what it would take to implement this functionality for aotm pkg - one day maybe I'll fork and implement my features :-)
